### ISSUE TITLE
Please explain the why bit

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/draft-guide-reactive-service-testing#12]
Why should you write tests using MicroShed testing? 
I guess you should focus on why mocking is difficult and test the real scenario as well as the speed etc.

**Comment by MaiHameed** [comment]
This has been explained in this blip:
![image](https://user-images.githubusercontent.com/26514093/78930774-a917ef80-7a72-11ea-9a12-a6b0b17ef1ec.png)

Please let me know if you think it requires more details @Emily-Jiang

**Comment by Emily-Jiang** [comment]
Can you explain why mocking is not good?

**Comment by MaiHameed** [comment]
Thoughts on adding the following paragraph before the paragraph I shared above?

> Sometimes tests might pass in development and testing (dev/test) environments, but fail in production because the application is running differently in production than it is in dev/test. Fortunately, you can minimize these parity issues between development and production by testing your application in the same Docker container that you’ll use in production.

**Comment by MaiHameed** [comment]
Updated site here: http://lgdev1.fyre.ibm.com:4020/guides/reactive-service-testing.html#testing-your-containers

Updated paragraph:
![image](https://user-images.githubusercontent.com/26514093/79478162-095de280-7fd9-11ea-8488-42b234655261.png)

**Comment by Emily-Jiang** [comment]
I would add something like this to justify why it is important to use MicroShed for this kind of microservice testing.

Sometimes, mocking framework can be used to test your microservice. However, in the system involving with Kafka, mocking is very difficult to mirror the live system. Therefore, MicroShed Testing is a best fit for testing Reactive Messaging with messaging broker involved.

**Comment by MaiHameed** [comment]
Closing, please let me know if you still have some additional comments!
