### ISSUE TITLE
Further comments on Inventory service

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/draft-guide-reactive-service-testing#28]
1. Should Testing using the Kafka consumer client be Testing using the Kafka producer client? I saw the Producer Client is used instead of Kafak consumer client.
2. Can you also explain the RestClient 
 @RESTClient
    public static InventoryResource inventoryResource;
and then show what InventorResource looks like.

**Comment by MaiHameed** [comment]
Explanation has been added at the end of this section: http://lgdev1.fyre.ibm.com:4020/guides/reactive-service-testing.html#testing-your-containers-2
