### ISSUE TITLE
Dev content review

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-reactive-service-testing#29]
- [x] Title -> "Testing reactive Java microservices"
- [x] Short description -> "Learn how to use Kafka client APIs and MicroShed Testing to test reactive Java microservices."
- [x] Need to sync up "What is MicroProfile Reactive Messaging?" with the reactive guide
- [x] you checked `RUN configure.sh` is no need in the Dockerfile?
- [x] InventoryServiceIT.java
  - better not use "cpu"
     - cpuProducer -> producer
     - cpuConsumer -> consumer
     - cpuLoad -> systemLoad
     - update the assert message "CPU load..."
  - if systems size is 1, no need the for loop
- [x] SystemServiceIT.java
  - better not use "cpu"
  - are you sure only 1 record? System service generate messages every 15 secs. Try run the test in dev mode multiple times after waiting a while for each run

**Comment by MaiHameed** [comment]
> you checked RUN configure.sh is no need in the Dockerfile?

Yes, it's unnecessary, and this was also addressed during the MST UFO presentation today. The script can be uncommented for the production image, but for the continuous test development phase it can be commented out.

**Comment by MaiHameed** [comment]
> if systems size is 1, no need the for loop 

While the expected number of systems is 1, the loop and assertion is there to catch a potential situation where the number exceeds 1, and will fail the test case.
