### ISSUE TITLE
Peer Review: Win

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/draft-guide-reactive-service-testing#4]
Peer Review: review to be done by a peer member.

Functionality
---
- [x] Check that the guide has working instructions and sample code
- [x] Test the guide on 3 platforms: Mac, __Win__, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable

Formatting & Presentation
---
- [x] Check the quality of code according to the best coding practices
    - [x] Ensure that command substitutions use the `$(cmd)` format and not ``` `cmd` ```
    - [x] Ensure that the console output of the integrated tests do not include the `[INFO]` tab
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid).
- [x] Check the `attribution` statement is accurate for the guide
- [ ] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility:
- [x] Additional tests where applicable:
    - [x] Define test coverage and review with team (including guide contributor, if available)
    - [x] Define detail test cases
    - [x] Consider corner cases targeting the specific guide
    - [x] Consider different platform tests, ie, Mac, Windows, Linux
    - [x] Consider corner cases UI tests
    - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
    - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately)
- [x] Consider SEO title and description for the guides
- [ ] Ensure automated test is enable, set up with Travis CI, and able to schedule tests
- [x] Run `diff -r start/ finish/` and there’s no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility:
- [x] Check the appearance of the guide on test site for the following items:
    - [x] Table of contents
    - [x] Headings
    - [x] Paragraphs
    - [x] code snippets
    - [x] outputs
    - [x] links
    - [x] hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by DannyS03** [comment]
# Formatting & Presentation
## What you’ll learn
- Might be better to have first paragraph at the end of the section.
<img width="574" alt="image" src="https://user-images.githubusercontent.com/25497083/77549875-c3ed4000-6e86-11ea-8cd6-8c4acd25f30e.png">

## Creating the tests
### Configuring your containers
- [ ] comma after `Now`.
<img width="552" alt="image" src="https://user-images.githubusercontent.com/25497083/77550030-fac35600-6e86-11ea-99b6-67b0a26cc5ae.png">

- [ ] Perhaps a good idea to create a hotspot for the class; the arrowhead already references the codepane.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/25497083/77550087-0c0c6280-6e87-11ea-91da-b5ce2b22270a.png">

- [ ] hotspot to explain the **@Container** annotation before discussing each container.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/25497083/77550148-1e869c00-6e87-11ea-9f97-4a86c5c58f27.png">

### Testing your containers
- [ ] To transmit messages to a stream, they will need to be serialized into bytes. Kafka has its own default serializer, **however,** a customer serializer has been provided for you **and is** configured to the producer’s valueSerializer.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/25497083/77550291-55f54880-6e87-11ea-840f-3467f502a24e.png">

- [ ] comma after `stream`.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/25497083/77550383-71605380-6e87-11ea-9e78-50de0a73006b.png">

## Running the tests
- [ ] Open Liberty development mode automatically recompiles and **updates** your test code changes.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/25497083/77550436-8210c980-6e87-11ea-9ab4-20b8f4643ca7.png">

- [ ] All of the other microservices in the application contain similar tests**;** feel free to try them out with the same commands in their respective directories.
<img width="549" alt="image" src="https://user-images.githubusercontent.com/25497083/77550499-905ee580-6e87-11ea-96d8-17a3c91919f9.png">

-----------
- consider changing time to **20 mins** or  **25 mins**
**Note:**
```
Only in start/kitchen/src/test/java/it/io/openliberty/guides/kitchen: .gitkeep
Only in finish/kitchen: target
Only in finish/models: target
Only in finish/openLibertyCafe: target
Only in finish/order: target
Only in start/: scripts
Only in finish/servingWindow: target
Only in finish/status: target
```

# Functionality
-

**Comment by MaiHameed** [comment]
> * Might be better to have first paragraph at the end of the section.

Following other guide's formatting, it always starts with an explanation of what the user will learn, then dive deeper into the definitions in the next couple of paragraphs. See [here](https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging.html#what-youll-learn) and [here](https://draft-guides.mybluemix.net/guides/microshed-testing.html)

**Comment by MaiHameed** [comment]
> [ ] Perhaps a good idea to create a hotspot for the class; the arrowhead already references the codepane.

What do you mean by this?

**Comment by MaiHameed** [comment]
> Only in start/kitchen/src/test/java/it/io/openliberty/guides/kitchen: .gitkeep
> Only in finish/kitchen: target
> Only in finish/models: target
> Only in finish/openLibertyCafe: target
> Only in finish/order: target
> Only in start/: scripts
> Only in finish/servingWindow: target
> Only in finish/status: target

This is due to the `target/` directory being created after running `mvn package` and does not exist with a fresh pull.

**Comment by MaiHameed** [comment]
> * In using development mode in the guide, shouldn't we mention running `mvn liberty:run` before the alternative `mvn verify`, to match how testing is presented in the guide.

What do you mean by this?

**Comment by MaiHameed** [comment]
> Note: when using windows containers.

Is this when using dev mode to run tests? Or `mvn verify`?

**Comment by DannyS03** [comment]
> > [ ] Perhaps a good idea to create a hotspot for the class; the arrowhead already references the codepane.
> 
> What do you mean by this?

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/25497083/77571071-205e5880-6ea3-11ea-81ec-081aa600c9e9.png">

- The arrow head already references the class. Suggesting that the hotspot highlights the actual class rather than act as a file hotspot (similar to other guides).

<img width="607" alt="image" src="https://user-images.githubusercontent.com/25497083/77571201-50a5f700-6ea3-11ea-873e-dbd3d92df14f.png">

**Comment by DannyS03** [comment]
> > * In using development mode in the guide, shouldn't we mention running `mvn liberty:run` before the alternative `mvn verify`, to match how testing is presented in the guide.
> 
> What do you mean by this?

Basically, referring to the `Try what you'll build` section where this could be outside the `Try what you'll build section` but still within `Getting started`.

- Since the user is using the same reactive messaging application... would it be a good idea to run the liberty server in the foreground (which includes the finished application) just as a way to showcase the application that will be used for testing - in the event the user does not engage in the **Creating asynchronous reactive microservices using MicroProfile Reactive Messaging** guide.

**Comment by DannyS03** [comment]
> > Note: when using windows containers.
> 
> Is this when using dev mode to run tests? Or `mvn verify`?

This is when running `mvn verify`.

**Comment by DannyS03** [comment]
> > * Might be better to have first paragraph at the end of the section.
> 
> Following other guide's formatting, it always starts with an explanation of what the user will learn, then dive deeper into the definitions in the next couple of paragraphs. See [here](https://draft-guides.mybluemix.net/guides/microprofile-reactive-messaging.html#what-youll-learn) and [here](https://draft-guides.mybluemix.net/guides/microshed-testing.html)

- Sorry, also meant to mention that you should replace the first paragraph with a `You will learn...` statement as the current content sounds more concluding and would suite better after introducing Microprofile Reactive Messaging and MicroShed Testing, you know what I mean?

**Comment by MaiHameed** [comment]
> > > * In using development mode in the guide, shouldn't we mention running `mvn liberty:run` before the alternative `mvn verify`, to match how testing is presented in the guide.
> > 
> > 
> > What do you mean by this?
> 
> Basically, referring to the `Try what you'll build` section where this could be outside the `Try what you'll build section` but still within `Getting started`.
> 
> * Since the user is using the same reactive messaging application... would it be a good idea to run the liberty server in the foreground (which includes the finished application) just as a way to showcase the application that will be used for testing - in the event the user does not engage in the **Creating asynchronous reactive microservices using MicroProfile Reactive Messaging** guide.

It's better to keep it modular. If the user does not check out the Reactive Messaging guide, the assumption is that they are either not interested or already know it. In either cases adding an app display would be redundant.

**Comment by MaiHameed** [comment]
> > > Note: when using windows containers.
> > 
> > 
> > Is this when using dev mode to run tests? Or `mvn verify`?
> 
> This is when running `mvn verify`.
> 
> It works as expected with _Linux containers._

I assume this is when you switch between Linux or Win containers within the Docker Desktop settings directly yes? If so I'll add a sentence telling the user to ensure that they're using Linux containers.

**Comment by DannyS03** [comment]
> > > > Note: when using windows containers.
> > > 
> > > 
> > > Is this when using dev mode to run tests? Or `mvn verify`?
> > 
> > 
> > This is when running `mvn verify`.
> > It works as expected with _Linux containers._
> 
> I assume this is when you switch between Linux or Win containers within the Docker Desktop settings directly yes? If so I'll add a sentence telling the user to ensure that they're using Linux containers.

Yes when switching between Linux and Win containers.

**Comment by DannyS03** [comment]
Feedback addressed and discussed.
