### ISSUE TITLE
Laura's review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-reactive-service-testing#41]
Looks good. Nice work.

Where I've copied some of the text, I've lost your highlighting (eg monospace) - assume the highlighting should be there as well. If my comment is to change the highlighting, I'll say that explicitly.

General style comment:
- [x] Throughout, when talking about how a technology works, always use the present tense (eg "the service produces messages", not "the service will produce messages"). Only use the future tense (mainly in the what you'll learn section) when you're talking about what will happen to the user in the course of doing the guide (eg "you'll learn about x", "you'll create an app that does x"). If in doubt, use the present tense, always. Future tense adds unnecessary words and can make sentences harder to read.

Other than where I've provided a new draft of the What You'll Learn section, everything else is small style things that should be fixed but should be quick to do. You'll get less ID reviewer feedback that way too. :)

- [x] "Java reactive messaging services" - Is this the right description for them or should it be "Java reactive web services"? I'm not certain but they're not really "messaging services", they just use messaging to communicate (messaging isn't their purpose, is what I'm attempting to say!).
- [x] Try and use "reactive Java" with the words in the same order consistently throughout, rather than switching. In general, try to use any terms consistently throughout (you don't need to make it varied in technical documentation, it can just add confusion for the reader).
- [x] Change "Learn how to use Kafka client APIs and MicroShed Testing to test reactive Java microservices." to something like "Learn how to test Java reactive microservices in true-to-production environments using MicroShed Testing". Switch the word order around to focus on the main point first - the user isn't here to learn about MicroShed Testing or Kafka APIs; they're here to learn about testing primarily.
- What you'll learn section - as YK suggested, start with testing:
  - [x] Can we have a copy of the diagram that shows the Kafka message broker between the producer and consumer services, just for illustration to help the user visualise the scenario app?
  - [x] I think you can remove all the duplication of the other guide and just point them to the other guide after a brief summary. Try replacing the whole section with this then see if @yeekangc thinks it reads ok without so much detail. We usually keep this section quite short; the reactive messaging guide is unusually long so we shouldn't really mimic that for length.
  >
  >You will learn how to write integration tests for reactive Java microservices and to run the tests in true-to-production environments using containers with MicroShed Testing (link to project site). MicroShed Testing runs your containerized application from outside the container so that you are testing the exact same image that runs in production. The reactive application in this guide sends and receives messages between services using an external message broker, Apache Kafka (link). Using an external message broker enables asynchronous communications between services so that requests are non-blocking and decoupled from responses. You can learn more about Java reactive services that use an external message broker to manage communications in the Creating reactive Java microservices (link) guide.
  >
  >== True-to-production integration testing with MicroShed Testing
  >
  >Tests sometimes pass during the development and testing stages of an application's lifecycle but then fail in production because the environment in which the application is running is different. While you can create mock objects and custom setups to try to minimize differences between environments, it is difficult to mimic a production system for an application that uses an external messaging system like Kafka. MicroShed Testing addresses this problem by enabling you to test your application in the same Docker container, or containers, that you'll use in production. This means that the environment remains the same throughout the application's lifecycle, from development, through testing, and into production. You can learn more about MicroShed Testing in the the Testing a MicroProfile or Jakarta EE application (link) guide.

  - [ ] NB, I'm not totally keen on the phrase "true-to-production" as it seems a bit clunky so if you have any better suggestions, feel free. I would go with "production-like" but the point is that it's not just "like" production, it's the same as production.
- Getting started section - looks good.
- Testing using the Kafka consumer client - minor style things:
  - [x] Don't need "provided" in the first sentence of the second para.
  - [x] First time you mention Kafka in this para, maybe say "Kafka message broker" as that's the important part.
  - [x] Don't shorten MicroShed Testing to "(MST)". Just say MicroShed Testing each time. You have literally two mentions of "MST" so there's no point. If you had more, I'd say it's fine in this situation to shorten to "MicroShed" after the first mention. But I think MicroShed Testing is just fine.
  - [x] "in your Maven project system/ and inventory/ pom.xml files." looks a bit weird with that highlighting. Could it be change to "in the Maven pom.xml files for the system and inventory services."
  - [x] Rephrase the paragraph starting "Note that this guide..." to:
  > The running system service searches for a Kafka topic to push its messages to. However, as there are not yet any running Kafka services, the system service throws some errors. Later in the guide, you will write and run tests that start a Kafka test container for the system service to communicate. This will resolve the errors that you see now.
  - [x] "You will need to create a class to externalize your container configurations." - make it present tense and more concise: "Create a class to externalize your container configurations."
  - [x] "an application container that will be started up and used in the tests" -> "an application container that is started up and used in the tests" (present tense)
  - [x] Change "There are two containers that will be used for testing the system service. First is the kafka container that the system service will be producing messages to. Second is the system container, which uses the same container that you built." to "Two containers are used for testing the system service: the system container, which you have built, and the kafka container to which the system service sends messages." (again, present tense and more concise)
  - [x] "should wait"? Or "must wait"? If it must wait, say so. "should" is vague and implies circumstances in which it might not...in which case you should say why (I don't think that's the case though here?).
  - [x] "Now you can start writing your test that will use the configured containers." -> "Now you can start writing the test that uses the configured containers." or "...your test to use the...".
  - [x] "from the systemLoadTopic topic from the kafka container. " -> "from the systemLoadTopic topic in the kafka container. "?
  - [x] "they will need to be deserialized " -> "they need to be deserialized "
  - [x] "Kafka has its own default deserializer, however, a custom deserializer has been provided for you, and is configured to the consumers’s valueDeserializer and has been implemented in the SystemLoad class." to "Kafka has its own default deserializer, but a custom deserializer has been provided for you. The deserializer is configured to the consumers’s valueDeserializer and is implemented in the SystemLoad class."
  - [x] "The running system service container will produce messages to the systemLoad Kafka topic, as denoted by the @Outgoing annotation. The testCpuStatus() test method will poll() records from Kafka every three seconds until the timeout limit. It will then verify that the record polled matched the expected record." to "The running system service container produces messages to the systemLoad Kafka topic, as denoted by the @Outgoing annotation. The testCpuStatus() test method polls records from Kafka every three seconds until the timeout limit. It then verifies that the record polled matches the expected record." (don't use the method name like `poll()` as part of the sentence; it reads a bit awkwardly but is also a problem if we translate)
- Testing...producer client section
  - [x] Again, make sure to use present tense throughout (I won't call them all out).
  - [x] "is the Kafka and inventory containers." should be "are the .... containers."
  - [x] "utilizes" -> "uses" (it's simpler and clearer)
  - [x] "The config annotation does not include a topic for the client to produce messages to, as it has the flexibility to produce messages to any topic, and is shown producing messages to the systemLoadTopic topic." -> "The @KafkaProducerConfig annotation does not include a topic for the client to produce messages to because it has the flexibility to produce messages to any topic. It is shown producing messages to the systemLoadTopic topic." Does that still mean the same thing? The sentence wasn't very clear and didn't quite make sense the way it was structured.
    - [x] When it says "is shown" - where is that shown? Can you clarify that?
  - [x] "via a cold start" -> "from a cold start"

**Comment by yeekangc** [comment]
I will go with "reactive Java", "reactive Java microservices", "reactive Java applications".  +1 to use the same word order consistently.

The revised intro looks nice.  Thank you, @lauracowen!

Yes, "true-to-production" is a bit clunky.  Then, it's more accurate and a term that MicroShed Testing uses itself.  I am fine if we have better alternatives.  Feel free to chime in, @aguibert.

**Comment by MaiHameed** [comment]
Thanks for the review @lauracowen! I addressed all the ticked off points, a couple of comments:

> NB, I'm not totally keen on the phrase "true-to-production"
- I don't have any good alternatives, so I'm leaving it.

> When it says "is shown" - where is that shown? Can you clarify that?
- I rewrote this to `It is set to produce messages` since the hotspot highlights the following line:
```producer.send(new ProducerRecord<String, SystemLoad>("systemLoadTopic", sl));```
  which shows the topic being set to the `systemLoadTopic`

The latest version can be found here: https://github.com/OpenLiberty/draft-guide-reactive-service-testing/pull/40, please re-review and let me know if it all looks good to you.
