### ISSUE TITLE
incorrect page-tags and page-related-guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-reactive-service-testing#7]
```
:page-tags: ['MicroProfile', 'Jakarta EE', 'Microservices'
:page-related-guides: ['microprofile-reactive-messaging'
```
- [x] both missing `]`
- [x] add all other reactive guides and async guide

**Comment by MaiHameed** [comment]
Addressed in c3084e998ea258a51efb1daf8788ac8a8ab58e18 and 24dfc3b84309168c4792828eb6e58425c789a3ef
